# Generated by Django 3.1.1 on 2020-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200916_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
