# Generated by Django 3.1.1 on 2020-09-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contact_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
